### ISSUE TITLE
Hinzufügen - Implementation

### ISSUE THREAD

**Issue by fabiovitalba** [fabiovitalba/maker-lab-project-2023-24#3]
Scenario #3 - Hinzufügen

- Input Barcode
  - _Achtung_: Barcodes auf Lebensmitteln sind normalerweise codiert (EAN, GS1) und müssten vielleicht speziell ausgewertet werden. Das muss nachdem die Scanner-Komponente verfügbar ist, muss das geprüft werden.
- Input Verfallsdatum
- Input Menge, Default 1

**Comment by daencel** [comment]
hinzufügen über terminal implementiert, über camera TODO

**Comment by fabiovitalba** [comment]
Wurde über barcode scanner getestet und funktioniert
